"""Increment 13: giving mirror and credentials

Revision ID: 0dc2975aa286
Revises: fd019c06a90b
Create Date: 2026-09-03 18:09:14.708338

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0dc2975aa286'
down_revision = 'fd019c06a90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('public_key', sa.String(length=200), nullable=True),
    sa.Column('private_key_encrypted', sa.Text(), nullable=True),
    sa.Column('organization_ref', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending_setup', 'active', 'error')", name=op.f('ck_integration_credential_ck_integration_credential_status')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_integration_credential_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_credential')),
    sa.UniqueConstraint('church_id', 'provider', name='uq_integration_credential_provider')
    )
    with op.batch_alter_table('integration_credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_credential_church_id'), ['church_id'], unique=False)

    op.create_table('external_gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_txn_id', sa.String(length=120), nullable=False),
    sa.Column('provider_donor_ref', sa.String(length=120), nullable=True),
    sa.Column('donor_name', sa.String(length=160), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('fund_name', sa.String(length=160), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('matched_by_user_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("match_status IN ('unmatched', 'matched', 'ignored')", name=op.f('ck_external_gift_ck_external_gift_match_status')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_external_gift_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_by_user_id'], ['user.id'], name=op.f('fk_external_gift_matched_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_external_gift_person_id_person'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_gift')),
    sa.UniqueConstraint('church_id', 'provider', 'provider_txn_id', name='uq_external_gift_txn')
    )
    with op.batch_alter_table('external_gift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_gift_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_gift_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_gift_church_date', ['church_id', 'received_on'], unique=False)
        batch_op.create_index('ix_gift_church_person_date', ['church_id', 'person_id', 'received_on'], unique=False)
        batch_op.create_index('ix_gift_church_unmatched', ['church_id', 'match_status'], unique=False)

    op.create_table('external_recurring_gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=False),
    sa.Column('provider_donor_ref', sa.String(length=120), nullable=True),
    sa.Column('donor_name', sa.String(length=160), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_charge_on', sa.Date(), nullable=True),
    sa.Column('last_success_on', sa.Date(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_external_recurring_gift_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_external_recurring_gift_person_id_person'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_recurring_gift')),
    sa.UniqueConstraint('church_id', 'provider', 'provider_ref', name='uq_external_recurring_gift_ref')
    )
    with op.batch_alter_table('external_recurring_gift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_recurring_gift_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_recurring_gift_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_recurring_church_person', ['church_id', 'person_id'], unique=False)
        batch_op.create_index('ix_recurring_church_status_seen', ['church_id', 'status', 'last_success_on'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_recurring_gift', schema=None) as batch_op:
        batch_op.drop_index('ix_recurring_church_status_seen')
        batch_op.drop_index('ix_recurring_church_person')
        batch_op.drop_index(batch_op.f('ix_external_recurring_gift_person_id'))
        batch_op.drop_index(batch_op.f('ix_external_recurring_gift_church_id'))

    op.drop_table('external_recurring_gift')
    with op.batch_alter_table('external_gift', schema=None) as batch_op:
        batch_op.drop_index('ix_gift_church_unmatched')
        batch_op.drop_index('ix_gift_church_person_date')
        batch_op.drop_index('ix_gift_church_date')
        batch_op.drop_index(batch_op.f('ix_external_gift_person_id'))
        batch_op.drop_index(batch_op.f('ix_external_gift_church_id'))

    op.drop_table('external_gift')
    with op.batch_alter_table('integration_credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_credential_church_id'))

    op.drop_table('integration_credential')
    # ### end Alembic commands ###
