"""Temporary passwords issued by staff

Revision ID: 157dcec25195
Revises: 7513bff9d292
Create Date: 2026-09-17 12:24:17.731765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157dcec25195'
down_revision = '7513bff9d292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
