"""Password reset tokens and session versioning

Revision ID: 1b05a93c764f
Revises: ad92028f3880
Create Date: 2026-09-02 00:11:53.198563

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1b05a93c764f'
down_revision = 'ad92028f3880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_password_reset_token_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_password_reset_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_token'))
    )
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_token_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reset_church_user', ['church_id', 'user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_reset_token_hash', ['token_hash'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index('ix_reset_token_hash')
        batch_op.drop_index('ix_reset_church_user')
        batch_op.drop_index(batch_op.f('ix_password_reset_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_church_id'))

    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
