"""Allow a household to share one email address

Revision ID: 1e08ad4ffa48
Revises: 0dc2975aa286
Create Date: 2026-09-03 18:11:59.149974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e08ad4ffa48'
down_revision = '0dc2975aa286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_person_church_email'), type_='unique')
        batch_op.create_index('ix_person_church_email', ['church_id', 'email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index('ix_person_church_email')
        batch_op.create_unique_constraint(batch_op.f('uq_person_church_email'), ['church_id', 'email'])

    # ### end Alembic commands ###
