"""song charts

Revision ID: 1eb45d68a46c
Revises: 248e3a1af709
Create Date: 2026-09-21 19:00:22.936272

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1eb45d68a46c'
down_revision = '248e3a1af709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_name', sa.String(length=120), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_song_chart_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('fk_song_chart_song_id_song'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], name=op.f('fk_song_chart_uploaded_by_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_song_chart'))
    )
    with op.batch_alter_table('song_chart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_chart_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_song_chart_church_song', ['church_id', 'song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_chart_song_id'), ['song_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_chart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_chart_song_id'))
        batch_op.drop_index('ix_song_chart_church_song')
        batch_op.drop_index(batch_op.f('ix_song_chart_church_id'))

    op.drop_table('song_chart')
    # ### end Alembic commands ###
