"""Increment 11: kids check-in sessions and checkins

Revision ID: 200c8e06e04d
Revises: 3dd7d4dc6b52
Create Date: 2026-09-02 11:53:49.596596

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '200c8e06e04d'
down_revision = '3dd7d4dc6b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_checkin_session_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkin_session'))
    )
    with op.batch_alter_table('checkin_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_session_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_checkin_session_church_time', ['church_id', 'starts_at'], unique=False)
        batch_op.create_index('ix_checkin_session_open', ['church_id', 'is_open'], unique=False)

    op.create_table('checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('household_name', sa.String(length=160), nullable=True),
    sa.Column('pickup_code', sa.String(length=8), nullable=False),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_in_by_user_id', sa.Integer(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_by_user_id', sa.Integer(), nullable=True),
    sa.Column('collected_by', sa.String(length=160), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by_user_id'], ['user.id'], name=op.f('fk_checkin_checked_in_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checked_out_by_user_id'], ['user.id'], name=op.f('fk_checkin_checked_out_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_checkin_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_checkin_household_id_household'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_checkin_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['checkin_session.id'], name=op.f('fk_checkin_session_id_checkin_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkin')),
    sa.UniqueConstraint('session_id', 'person_id', name='uq_checkin_person_id')
    )
    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_checkin_church_person', ['church_id', 'person_id'], unique=False)
        batch_op.create_index('ix_checkin_church_present', ['church_id', 'session_id', 'checked_out_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_checkin_session_code', ['session_id', 'pickup_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_session_id'))
        batch_op.drop_index('ix_checkin_session_code')
        batch_op.drop_index(batch_op.f('ix_checkin_person_id'))
        batch_op.drop_index('ix_checkin_church_present')
        batch_op.drop_index('ix_checkin_church_person')
        batch_op.drop_index(batch_op.f('ix_checkin_church_id'))

    op.drop_table('checkin')
    with op.batch_alter_table('checkin_session', schema=None) as batch_op:
        batch_op.drop_index('ix_checkin_session_open')
        batch_op.drop_index('ix_checkin_session_church_time')
        batch_op.drop_index(batch_op.f('ix_checkin_session_church_id'))

    op.drop_table('checkin_session')
    # ### end Alembic commands ###
