"""Increment 14: sequence enrollments

Revision ID: 223dc7c5ea44
Revises: 1e08ad4ffa48
Create Date: 2026-09-03 18:24:25.545624

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '223dc7c5ea44'
down_revision = '1e08ad4ffa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('sequence_code', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steps_sent', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=40), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'stopped')", name=op.f('ck_sequence_enrollment_ck_sequence_enrollment_status')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_sequence_enrollment_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_sequence_enrollment_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sequence_enrollment')),
    sa.UniqueConstraint('person_id', 'sequence_code', name='uq_sequence_enrollment_sequence_code')
    )
    with op.batch_alter_table('sequence_enrollment', schema=None) as batch_op:
        batch_op.create_index('ix_enrollment_church_person', ['church_id', 'person_id'], unique=False)
        batch_op.create_index('ix_enrollment_due', ['church_id', 'status', 'next_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequence_enrollment_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequence_enrollment_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence_enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequence_enrollment_person_id'))
        batch_op.drop_index(batch_op.f('ix_sequence_enrollment_church_id'))
        batch_op.drop_index('ix_enrollment_due')
        batch_op.drop_index('ix_enrollment_church_person')

    op.drop_table('sequence_enrollment')
    # ### end Alembic commands ###
