"""church ccli license number

Revision ID: 248e3a1af709
Revises: d4c81b6f2a37
Create Date: 2026-09-21 18:31:47.816689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248e3a1af709'
down_revision = 'd4c81b6f2a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ccli_license_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.drop_column('ccli_license_number')

    # ### end Alembic commands ###
