"""Increment 5: household check-in PIN

Revision ID: 367ae9e93933
Revises: f92056a65d90
Create Date: 2026-08-18 20:58:57.999268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367ae9e93933'
down_revision = 'f92056a65d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkin_pin', sa.String(length=6), nullable=True))
        batch_op.create_index(batch_op.f('ix_household_checkin_pin'), ['checkin_pin'], unique=False)
        batch_op.create_unique_constraint('uq_household_checkin_pin', ['church_id', 'checkin_pin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_constraint('uq_household_checkin_pin', type_='unique')
        batch_op.drop_index(batch_op.f('ix_household_checkin_pin'))
        batch_op.drop_column('checkin_pin')

    # ### end Alembic commands ###
