"""Increment 3: contact log, next steps, ownership

Revision ID: 3755f028bed8
Revises: 751cbcc6755a
Create Date: 2026-08-18 13:58:20.286639

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3755f028bed8'
down_revision = '751cbcc6755a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('logged_by_name', sa.String(length=120), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('call', 'text', 'email', 'in_person', 'other')", name=op.f('ck_contact_log_ck_contact_log_method')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_contact_log_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['user.id'], name=op.f('fk_contact_log_logged_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_contact_log_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_log'))
    )
    with op.batch_alter_table('contact_log', schema=None) as batch_op:
        batch_op.create_index('ix_contact_church_person_time', ['church_id', 'person_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_contact_church_time', ['church_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_log_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_log_person_id'), ['person_id'], unique=False)

    op.create_table('next_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=120), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'done', 'dropped')", name=op.f('ck_next_step_ck_next_step_status')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_next_step_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_next_step_created_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('fk_next_step_owner_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_next_step_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_next_step'))
    )
    with op.batch_alter_table('next_step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_next_step_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_next_step_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_next_step_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_step_church_owner_status', ['church_id', 'owner_user_id', 'status'], unique=False)
        batch_op.create_index('ix_step_church_person_status', ['church_id', 'person_id', 'status'], unique=False)
        batch_op.create_index('ix_step_church_status_due', ['church_id', 'status', 'due_on'], unique=False)

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('owner_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('owner_name', sa.String(length=120), nullable=True))
        batch_op.create_index('ix_person_church_contact', ['church_id', 'last_contact_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_person_owner_user_id_user'), 'user', ['owner_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_person_owner_user_id_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_person_owner_user_id'))
        batch_op.drop_index('ix_person_church_contact')
        batch_op.drop_column('owner_name')
        batch_op.drop_column('owner_user_id')
        batch_op.drop_column('last_contact_at')

    with op.batch_alter_table('next_step', schema=None) as batch_op:
        batch_op.drop_index('ix_step_church_status_due')
        batch_op.drop_index('ix_step_church_person_status')
        batch_op.drop_index('ix_step_church_owner_status')
        batch_op.drop_index(batch_op.f('ix_next_step_person_id'))
        batch_op.drop_index(batch_op.f('ix_next_step_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_next_step_church_id'))

    op.drop_table('next_step')
    with op.batch_alter_table('contact_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_log_person_id'))
        batch_op.drop_index(batch_op.f('ix_contact_log_church_id'))
        batch_op.drop_index('ix_contact_church_time')
        batch_op.drop_index('ix_contact_church_person_time')

    op.drop_table('contact_log')
    # ### end Alembic commands ###
