"""Increment 10: services, songs, teams, assignments

Revision ID: 3dd7d4dc6b52
Revises: ddedc3621d5a
Create Date: 2026-09-02 01:15:30.215772

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3dd7d4dc6b52'
down_revision = 'ddedc3621d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'sent')", name=op.f('ck_service_ck_service_status')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_service_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service'))
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_service_church_time', ['church_id', 'starts_at'], unique=False)

    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('ccli_number', sa.String(length=20), nullable=True),
    sa.Column('default_key', sa.String(length=10), nullable=True),
    sa.Column('tempo_bpm', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_song_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_song'))
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_song_church_title', ['church_id', 'title'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_team_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_team_church_name', ['church_id', 'name'], unique=False)

    op.create_table('service_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('key_override', sa.String(length=10), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('song', 'element')", name=op.f('ck_service_item_ck_service_item_kind')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_service_item_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_service_item_service_id_service'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('fk_service_item_song_id_song'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_item')),
    sa.UniqueConstraint('service_id', 'position', name='uq_service_item_position')
    )
    with op.batch_alter_table('service_item', schema=None) as batch_op:
        batch_op.create_index('ix_item_church_song', ['church_id', 'song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_item_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_item_service_id'), ['service_id'], unique=False)

    op.create_table('team_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_team_position_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_position_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_position')),
    sa.UniqueConstraint('team_id', 'name', name='uq_team_position_name')
    )
    with op.batch_alter_table('team_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_position_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_position_team_id'), ['team_id'], unique=False)

    op.create_table('service_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('position_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('invited', 'accepted', 'declined')", name=op.f('ck_service_assignment_ck_service_assignment_status')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_service_assignment_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_service_assignment_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['team_position.id'], name=op.f('fk_service_assignment_position_id_team_position'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_service_assignment_service_id_service'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_assignment')),
    sa.UniqueConstraint('service_id', 'person_id', 'position_id', name='uq_service_assignment_position_id')
    )
    with op.batch_alter_table('service_assignment', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_church_person', ['church_id', 'person_id', 'status'], unique=False)
        batch_op.create_index('ix_assignment_service_status', ['service_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_assignment_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_assignment_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_assignment_service_id'), ['service_id'], unique=False)

    op.create_table('team_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_team_membership_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_team_membership_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_membership_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_membership')),
    sa.UniqueConstraint('team_id', 'person_id', name='uq_team_membership_person_id')
    )
    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_membership_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_team_membership_church_person', ['church_id', 'person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_membership_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_membership_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_membership_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_membership_person_id'))
        batch_op.drop_index('ix_team_membership_church_person')
        batch_op.drop_index(batch_op.f('ix_team_membership_church_id'))

    op.drop_table('team_membership')
    with op.batch_alter_table('service_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_assignment_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_assignment_person_id'))
        batch_op.drop_index(batch_op.f('ix_service_assignment_church_id'))
        batch_op.drop_index('ix_assignment_service_status')
        batch_op.drop_index('ix_assignment_church_person')

    op.drop_table('service_assignment')
    with op.batch_alter_table('team_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_position_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_position_church_id'))

    op.drop_table('team_position')
    with op.batch_alter_table('service_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_item_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_item_church_id'))
        batch_op.drop_index('ix_item_church_song')

    op.drop_table('service_item')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index('ix_team_church_name')
        batch_op.drop_index(batch_op.f('ix_team_church_id'))

    op.drop_table('team')
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index('ix_song_church_title')
        batch_op.drop_index(batch_op.f('ix_song_church_id'))

    op.drop_table('song')
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index('ix_service_church_time')
        batch_op.drop_index(batch_op.f('ix_service_church_id'))

    op.drop_table('service')
    # ### end Alembic commands ###
