"""increment 0: church and church_domain

Revision ID: 531cc78ec1e1
Revises: 
Create Date: 2026-08-16 00:01:53.339591

"""
from alembic import op
import sqlalchemy as sa
import app.types


# revision identifiers, used by Alembic.
revision = '531cc78ec1e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('church',
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('accent_hex', sa.String(length=7), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=120), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('reply_to_email', sa.String(length=255), nullable=True),
    sa.Column('connect_card_enabled', sa.Boolean(), nullable=False),
    sa.Column('connect_card_intro', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_church')),
    sa.UniqueConstraint('slug', name=op.f('uq_church_slug'))
    )
    op.create_table('church_domain',
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified_at', app.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_church_domain_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_church_domain')),
    sa.UniqueConstraint('church_id', 'id', name=op.f('uq_church_domain_church_id_id')),
    sa.UniqueConstraint('host', name=op.f('uq_church_domain_host'))
    )
    with op.batch_alter_table('church_domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_church_domain_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_church_domain_church_id_is_primary', ['church_id', 'is_primary'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church_domain', schema=None) as batch_op:
        batch_op.drop_index('ix_church_domain_church_id_is_primary')
        batch_op.drop_index(batch_op.f('ix_church_domain_church_id'))

    op.drop_table('church_domain')
    op.drop_table('church')
    # ### end Alembic commands ###
