"""Self-registration: verification tokens and church toggle

Revision ID: 5a7df3a04bb1
Revises: 875f26d70811
Create Date: 2026-09-08 13:42:32.841616

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5a7df3a04bb1'
down_revision = '875f26d70811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_email_verification_token_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_email_verification_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_token'))
    )
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_token_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_token_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_verify_church_user', ['church_id', 'user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_verify_token_hash', ['token_hash'], unique=False)

    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_self_signup', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))

    # Backfill. Every account that exists before this migration was created by
    # a staff member, which is exactly the signal `email_verified_at` records.
    # Without this line the deploy locks out every existing user at every
    # church, including the person who would have to fix it.
    op.execute(
        "UPDATE \"user\" SET email_verified_at = created_at "
        "WHERE email_verified_at IS NULL"
    )

    # Every account that already exists was created by a staff member, which
    # is a stronger signal than a click in an inbox. Leaving them null would
    # lock out every existing user the moment this deploys.
    op.execute(
        "UPDATE \"user\" SET email_verified_at = created_at "
        "WHERE email_verified_at IS NULL"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')

    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.drop_column('allow_self_signup')

    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.drop_index('ix_verify_token_hash')
        batch_op.drop_index('ix_verify_church_user')
        batch_op.drop_index(batch_op.f('ix_email_verification_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_token_church_id'))

    op.drop_table('email_verification_token')
    # ### end Alembic commands ###
