"""team files

Revision ID: 600e3a135bae
Revises: c7e2a9f41d06
Create Date: 2026-09-20 12:50:40.748797

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '600e3a135bae'
down_revision = 'c7e2a9f41d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_name', sa.String(length=120), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_team_file_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_file_team_id_team'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], name=op.f('fk_team_file_uploaded_by_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_file'))
    )
    with op.batch_alter_table('team_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_file_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_team_file_church_team', ['church_id', 'team_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_file_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_file_team_id'))
        batch_op.drop_index('ix_team_file_church_team')
        batch_op.drop_index(batch_op.f('ix_team_file_church_id'))

    op.drop_table('team_file')
    # ### end Alembic commands ###
