"""resource covers and session minutes

Revision ID: 6dad82908131
Revises: de2973099ddb
Create Date: 2026-09-19 10:38:03.272352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dad82908131'
down_revision = 'de2973099ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('resource_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes', sa.Integer(), nullable=True))

    # Existing plans get different covers rather than six identical cards.
    op.execute("UPDATE resource SET cover = id % 6")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_session', schema=None) as batch_op:
        batch_op.drop_column('minutes')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
