"""Increment 0: church table

Revision ID: 7034dd7af5ac
Revises: 
Create Date: 2026-08-17 00:34:27.053987

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7034dd7af5ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('church',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('palette_key', sa.String(length=40), nullable=False),
    sa.Column('accent_hex', sa.String(length=7), nullable=True),
    sa.Column('logo_reversed_path', sa.String(length=255), nullable=True),
    sa.Column('app_name', sa.String(length=120), nullable=True),
    sa.Column('app_domain', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_domain', name='uq_church_custom_domain'),
    sa.UniqueConstraint('slug', name='uq_church_slug')
    )
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_church_custom_domain'), ['custom_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_church_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_church_slug'))
        batch_op.drop_index(batch_op.f('ix_church_custom_domain'))

    op.drop_table('church')
    # ### end Alembic commands ###
