"""Service types, templates, staffing needs, plan sections

Revision ID: 7513bff9d292
Revises: cb639f3bea0c
Create Date: 2026-09-16 03:26:20.072379

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7513bff9d292'
down_revision = 'cb639f3bea0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('default_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_service_type_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_type')),
    sa.UniqueConstraint('church_id', 'name', name='uq_service_type_name')
    )
    with op.batch_alter_table('service_type', schema=None) as batch_op:
        batch_op.create_index('ix_service_type_church', ['church_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_type_church_id'), ['church_id'], unique=False)

    op.create_table('service_template_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('song', 'element', 'header')", name=op.f('ck_service_template_item_ck_service_template_item_kind')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_service_template_item_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], name=op.f('fk_service_template_item_service_type_id_service_type'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], name=op.f('fk_service_template_item_song_id_song'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_template_item')),
    sa.UniqueConstraint('service_type_id', 'position', name='uq_service_template_item_position')
    )
    with op.batch_alter_table('service_template_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_template_item_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_template_item_service_type_id'), ['service_type_id'], unique=False)

    op.create_table('service_need',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('position_name', sa.String(length=120), nullable=True),
    sa.Column('wanted', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_service_need_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['team_position.id'], name=op.f('fk_service_need_position_id_team_position'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_service_need_service_id_service'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_need')),
    sa.UniqueConstraint('service_id', 'position_id', name='uq_service_need_position')
    )
    with op.batch_alter_table('service_need', schema=None) as batch_op:
        batch_op.create_index('ix_service_need_church', ['church_id', 'service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_need_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_need_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_need_service_id'), ['service_id'], unique=False)

    op.create_table('service_type_need',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('wanted', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_service_type_need_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['team_position.id'], name=op.f('fk_service_type_need_position_id_team_position'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], name=op.f('fk_service_type_need_service_type_id_service_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_type_need')),
    sa.UniqueConstraint('service_type_id', 'position_id', name='uq_service_type_need_position')
    )
    with op.batch_alter_table('service_type_need', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_type_need_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_type_need_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_type_need_service_type_id'), ['service_type_id'], unique=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_service_type_id'), ['service_type_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_service_service_type_id_service_type'), 'service_type', ['service_type_id'], ['id'], ondelete='SET NULL')

    # A plan can now carry section headers. The existing CHECK constraint
    # still lists only ('song', 'element'), and Alembic does not diff check
    # constraints, so it has to be replaced by hand.
    with op.batch_alter_table(
        'service_item',
        schema=None,
        table_kwargs={'sqlite_autoincrement': False},
    ) as batch_op:
        # op.f() marks the name as already final. Without it the naming
        # convention prepends its prefix a second time and the drop looks for
        # a constraint that was never called that.
        batch_op.drop_constraint(
            op.f('ck_service_item_ck_service_item_kind'), type_='check'
        )
        batch_op.create_check_constraint(
            'kind', "kind IN ('song', 'element', 'header')"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_service_service_type_id_service_type'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_service_service_type_id'))
        batch_op.drop_column('service_type_id')

    with op.batch_alter_table('service_type_need', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_type_need_service_type_id'))
        batch_op.drop_index(batch_op.f('ix_service_type_need_position_id'))
        batch_op.drop_index(batch_op.f('ix_service_type_need_church_id'))

    op.drop_table('service_type_need')
    with op.batch_alter_table('service_need', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_need_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_need_position_id'))
        batch_op.drop_index(batch_op.f('ix_service_need_church_id'))
        batch_op.drop_index('ix_service_need_church')

    op.drop_table('service_need')
    with op.batch_alter_table('service_template_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_template_item_service_type_id'))
        batch_op.drop_index(batch_op.f('ix_service_template_item_church_id'))

    op.drop_table('service_template_item')
    with op.batch_alter_table('service_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_type_church_id'))
        batch_op.drop_index('ix_service_type_church')

    op.drop_table('service_type')
    # ### end Alembic commands ###
