"""Increment 2: households, people, timeline

Revision ID: 751cbcc6755a
Revises: 452ea4e56641
Create Date: 2026-08-18 12:28:24.195937

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '751cbcc6755a'
down_revision = '452ea4e56641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address_line', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_household_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household'))
    )
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_household_church_name', ['church_id', 'name'], unique=False)

    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('stage_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_child', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage IN ('visitor', 'guest', 'attender', 'member', 'volunteer', 'disciple', 'leader')", name=op.f('ck_person_ck_person_stage')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_person_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_person_household_id_household'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
    sa.UniqueConstraint('church_id', 'email', name='uq_person_church_email')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_person_church_last_first', ['church_id', 'last_name', 'first_name'], unique=False)
        batch_op.create_index('ix_person_church_stage', ['church_id', 'stage'], unique=False)
        batch_op.create_index('ix_person_church_stage_since', ['church_id', 'stage', 'stage_since'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_stage'), ['stage'], unique=False)

    op.create_table('person_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('fk_person_event_actor_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_person_event_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_person_event_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_event'))
    )
    with op.batch_alter_table('person_event', schema=None) as batch_op:
        batch_op.create_index('ix_event_church_kind_time', ['church_id', 'kind', 'occurred_at'], unique=False)
        batch_op.create_index('ix_event_church_person_time', ['church_id', 'person_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_event_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_event_person_id'), ['person_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_person_id'), ['person_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_person_id_person'), 'person', ['person_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_person_id_person'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_person_id'))
        batch_op.drop_column('person_id')

    with op.batch_alter_table('person_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_event_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_event_church_id'))
        batch_op.drop_index('ix_event_church_person_time')
        batch_op.drop_index('ix_event_church_kind_time')

    op.drop_table('person_event')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_stage'))
        batch_op.drop_index(batch_op.f('ix_person_household_id'))
        batch_op.drop_index('ix_person_church_stage_since')
        batch_op.drop_index('ix_person_church_stage')
        batch_op.drop_index('ix_person_church_last_first')
        batch_op.drop_index(batch_op.f('ix_person_church_id'))

    op.drop_table('person')
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_index('ix_household_church_name')
        batch_op.drop_index(batch_op.f('ix_household_church_id'))

    op.drop_table('household')
    # ### end Alembic commands ###
