"""Chat reports, blocks, and community standards agreement

Revision ID: 763dfd13feab
Revises: 157dcec25195
Create Date: 2026-09-18 21:47:43.576737

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '763dfd13feab'
down_revision = '157dcec25195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_person_id', sa.Integer(), nullable=False),
    sa.Column('blocked_person_id', sa.Integer(), nullable=False),
    sa.Column('blocked_name', sa.String(length=120), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('blocker_person_id != blocked_person_id', name=op.f('ck_person_block_ck_person_block_not_self')),
    sa.ForeignKeyConstraint(['blocked_person_id'], ['person.id'], name=op.f('fk_person_block_blocked_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_person_id'], ['person.id'], name=op.f('fk_person_block_blocker_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_person_block_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_block')),
    sa.UniqueConstraint('blocker_person_id', 'blocked_person_id', name='uq_person_block_pair')
    )
    with op.batch_alter_table('person_block', schema=None) as batch_op:
        batch_op.create_index('ix_block_church_blocker', ['church_id', 'blocker_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_block_church_id'), ['church_id'], unique=False)

    op.create_table('message_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('reporter_person_id', sa.Integer(), nullable=True),
    sa.Column('reporter_name', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_name', sa.String(length=120), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open', 'removed', 'dismissed')", name=op.f('ck_message_report_ck_message_report_status')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_message_report_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_message_report_conversation_id_conversation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name=op.f('fk_message_report_message_id_message'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_person_id'], ['person.id'], name=op.f('fk_message_report_reporter_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['user.id'], name=op.f('fk_message_report_resolved_by_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_report')),
    sa.UniqueConstraint('message_id', 'reporter_person_id', name='uq_message_report_reporter')
    )
    with op.batch_alter_table('message_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_report_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_report_message_id'), ['message_id'], unique=False)
        batch_op.create_index('ix_report_church_status', ['church_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_accepted_at', sa.DateTime(timezone=True), nullable=True))

    # A new notification category, "moderation", for staff report alerts.
    # Both tables pin the allowed categories in a CHECK constraint written when
    # increment 4's migration ran. The model changed; the database would not
    # have, and every staff alert would have failed with an IntegrityError.
    # Alembic does not diff check constraints, so they are replaced by hand.
    #
    # The names are the doubled form the naming convention produced for the
    # originals, kept identical so the next replacement can find them.
    for table in ("outbox_message", "notification_preference"):
        name = f"ck_{table}_ck_{table}_category"
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.drop_constraint(op.f(name), type_="check")
            batch_op.create_check_constraint(
                op.f(name),
                "category IN ('account', 'kids_checkin', 'moderation', 'giving_receipt', 'welcome', 'next_step', 'group', 'announcement', 'digest')",
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('community_accepted_at')

    with op.batch_alter_table('message_report', schema=None) as batch_op:
        batch_op.drop_index('ix_report_church_status')
        batch_op.drop_index(batch_op.f('ix_message_report_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_report_church_id'))

    op.drop_table('message_report')
    with op.batch_alter_table('person_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_block_church_id'))
        batch_op.drop_index('ix_block_church_blocker')

    op.drop_table('person_block')
    # ### end Alembic commands ###
