"""Push subscriptions

Revision ID: 790cbe896349
Revises: 5a7df3a04bb1
Create Date: 2026-09-10 21:44:15.627227

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '790cbe896349'
down_revision = '5a7df3a04bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('endpoint_hash', sa.String(length=64), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_push_subscription_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_push_subscription_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_push_subscription_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscription')),
    sa.UniqueConstraint('endpoint_hash', name='uq_push_subscription_endpoint')
    )
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_index('ix_push_church_person', ['church_id', 'person_id'], unique=False)
        batch_op.create_index('ix_push_church_user', ['church_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscription_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscription_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscription_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscription_person_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscription_church_id'))
        batch_op.drop_index('ix_push_church_user')
        batch_op.drop_index('ix_push_church_person')

    op.drop_table('push_subscription')
    # ### end Alembic commands ###
