"""Increment 15: audit events

Revision ID: 82c0e7a2ffd8
Revises: 223dc7c5ea44
Create Date: 2026-09-03 18:39:12.233162

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '82c0e7a2ffd8'
down_revision = '223dc7c5ea44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('subject_type', sa.String(length=40), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('subject_label', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], name=op.f('fk_audit_event_actor_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_audit_event_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index('ix_audit_church_action', ['church_id', 'action', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_church_actor', ['church_id', 'actor_user_id'], unique=False)
        batch_op.create_index('ix_audit_church_time', ['church_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_church_id'), ['church_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_church_id'))
        batch_op.drop_index('ix_audit_church_time')
        batch_op.drop_index('ix_audit_church_actor')
        batch_op.drop_index('ix_audit_church_action')

    op.drop_table('audit_event')
    # ### end Alembic commands ###
