"""Increment 8: World English Bible verses

Revision ID: 875f26d70811
Revises: 82c0e7a2ffd8
Create Date: 2026-09-03 19:00:09.192684

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '875f26d70811'
down_revision = '82c0e7a2ffd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=40), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bible_verse')),
    sa.UniqueConstraint('book', 'chapter', 'verse', name='uq_bible_verse_ref')
    )
    with op.batch_alter_table('bible_verse', schema=None) as batch_op:
        batch_op.create_index('ix_bible_book_chapter', ['book', 'chapter', 'verse'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible_verse', schema=None) as batch_op:
        batch_op.drop_index('ix_bible_book_chapter')

    op.drop_table('bible_verse')
    # ### end Alembic commands ###
