"""Increment 6: resources, sessions, completions

Revision ID: ad92028f3880
Revises: 367ae9e93933
Create Date: 2026-09-01 23:57:23.679300

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ad92028f3880'
down_revision = '367ae9e93933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('reading_plan', 'next_steps', 'training', 'study', 'course')", name=op.f('ck_resource_ck_resource_kind')),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name=op.f('ck_resource_ck_resource_status')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_resource_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_resource_created_by_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource'))
    )
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_resource_church_status', ['church_id', 'status'], unique=False)

    op.create_table('resource_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('passage_ref', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_resource_session_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name=op.f('fk_resource_session_resource_id_resource'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_session')),
    sa.UniqueConstraint('resource_id', 'position', name='uq_resource_session_position')
    )
    with op.batch_alter_table('resource_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_session_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_session_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index('ix_session_church_resource', ['church_id', 'resource_id', 'position'], unique=False)

    op.create_table('session_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_session_completion_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_session_completion_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name=op.f('fk_session_completion_resource_id_resource'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['resource_session.id'], name=op.f('fk_session_completion_session_id_resource_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_completion')),
    sa.UniqueConstraint('person_id', 'session_id', name='uq_session_completion_session_id')
    )
    with op.batch_alter_table('session_completion', schema=None) as batch_op:
        batch_op.create_index('ix_completion_church_person', ['church_id', 'person_id', 'resource_id'], unique=False)
        batch_op.create_index('ix_completion_church_resource', ['church_id', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_completion_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_completion_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_completion_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_completion_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_completion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_completion_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_completion_resource_id'))
        batch_op.drop_index(batch_op.f('ix_session_completion_person_id'))
        batch_op.drop_index(batch_op.f('ix_session_completion_church_id'))
        batch_op.drop_index('ix_completion_church_resource')
        batch_op.drop_index('ix_completion_church_person')

    op.drop_table('session_completion')
    with op.batch_alter_table('resource_session', schema=None) as batch_op:
        batch_op.drop_index('ix_session_church_resource')
        batch_op.drop_index(batch_op.f('ix_resource_session_resource_id'))
        batch_op.drop_index(batch_op.f('ix_resource_session_church_id'))

    op.drop_table('resource_session')
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_index('ix_resource_church_status')
        batch_op.drop_index(batch_op.f('ix_resource_church_id'))

    op.drop_table('resource')
    # ### end Alembic commands ###
