"""baseline: phase 1 schema as deployed

Revision ID: b57ec347cc74
Revises: 
Create Date: 2026-08-14 21:37:22.811607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57ec347cc74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('tithely_form_id', sa.String(length=120), nullable=True),
    sa.Column('tithely_give_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('kids_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_starts_at'), ['starts_at'], unique=False)

    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('stuck_after_days', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'position', name='uq_stage_position')
    )
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stages_church_id'), ['church_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('requires_clearance', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'name', name='uq_team_name')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_church_id'), ['church_id'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active_record', sa.Boolean(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('stage_since', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'email', name='uq_person_email')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index('ix_person_stage', ['church_id', 'stage_id'], unique=False)

    op.create_table('access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_tokens_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_tokens_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=40), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('emailed_at', sa.DateTime(), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_church_id'), ['church_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('sequence_key', sa.String(length=60), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('last_step_sent', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('stop_reason', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'person_id', 'sequence_key', name='uq_enrollment')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_person_id'), ['person_id'], unique=False)

    op.create_table('giving_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('donor_name', sa.String(length=160), nullable=True),
    sa.Column('donor_email', sa.String(length=200), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('fund', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('given_at', sa.DateTime(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'external_id', name='uq_gift_external')
    )
    with op.batch_alter_table('giving_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giving_records_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_giving_records_person_id'), ['person_id'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('meeting_time', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_church_id'), ['church_id'], unique=False)

    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['guardian_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_households_church_id'), ['church_id'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.String(length=600), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_person_id'), ['person_id'], unique=False)

    op.create_table('service_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'person_id', 'role', name='uq_service_assignment')
    )
    with op.batch_alter_table('service_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_assignments_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_assignments_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_assignments_service_id'), ['service_id'], unique=False)

    op.create_table('service_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_elements_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_elements_service_id'), ['service_id'], unique=False)

    op.create_table('stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=True),
    sa.Column('to_stage_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['from_stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_events_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_events_person_id'), ['person_id'], unique=False)

    op.create_table('team_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'person_id', name='uq_team_member')
    )
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_memberships_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_memberships_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_memberships_team_id'), ['team_id'], unique=False)

    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('room', sa.String(length=60), nullable=False),
    sa.Column('allergies', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_active_record', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_household_id'), ['household_id'], unique=False)

    op.create_table('group_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'person_id', name='uq_group_member')
    )
    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_memberships_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_memberships_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_memberships_person_id'), ['person_id'], unique=False)

    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('room', sa.String(length=60), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.Column('checked_in_by', sa.String(length=120), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_ins_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_ins_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_ins_service_id'), ['service_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_ins_service_id'))
        batch_op.drop_index(batch_op.f('ix_check_ins_church_id'))
        batch_op.drop_index(batch_op.f('ix_check_ins_child_id'))

    op.drop_table('check_ins')
    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_memberships_person_id'))
        batch_op.drop_index(batch_op.f('ix_group_memberships_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_memberships_church_id'))

    op.drop_table('group_memberships')
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_household_id'))
        batch_op.drop_index(batch_op.f('ix_children_church_id'))

    op.drop_table('children')
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_memberships_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_memberships_person_id'))
        batch_op.drop_index(batch_op.f('ix_team_memberships_church_id'))

    op.drop_table('team_memberships')
    with op.batch_alter_table('stage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_events_person_id'))
        batch_op.drop_index(batch_op.f('ix_stage_events_church_id'))

    op.drop_table('stage_events')
    with op.batch_alter_table('service_elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_elements_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_elements_church_id'))

    op.drop_table('service_elements')
    with op.batch_alter_table('service_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_assignments_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_assignments_person_id'))
        batch_op.drop_index(batch_op.f('ix_service_assignments_church_id'))

    op.drop_table('service_assignments')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_person_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_church_id'))

    op.drop_table('interactions')
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_church_id'))

    op.drop_table('households')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_church_id'))

    op.drop_table('groups')
    with op.batch_alter_table('giving_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giving_records_person_id'))
        batch_op.drop_index(batch_op.f('ix_giving_records_church_id'))

    op.drop_table('giving_records')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_person_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_church_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_church_id'))

    op.drop_table('announcements')
    with op.batch_alter_table('access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_access_tokens_person_id'))
        batch_op.drop_index(batch_op.f('ix_access_tokens_church_id'))

    op.drop_table('access_tokens')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index('ix_person_stage')
        batch_op.drop_index(batch_op.f('ix_people_stage_id'))
        batch_op.drop_index(batch_op.f('ix_people_church_id'))

    op.drop_table('people')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_church_id'))

    op.drop_table('teams')
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stages_church_id'))

    op.drop_table('stages')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_starts_at'))
        batch_op.drop_index(batch_op.f('ix_services_church_id'))

    op.drop_table('services')
    op.drop_table('churches')
    # ### end Alembic commands ###
