"""service headcount

Revision ID: bb1b1997175b
Revises: a1f3c9d2e7b4
Create Date: 2026-09-19 11:53:47.123107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1b1997175b'
down_revision = 'a1f3c9d2e7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headcount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('headcount')

    # ### end Alembic commands ###
