"""Staff approval for self-registered people

Revision ID: cb639f3bea0c
Revises: 790cbe896349
Create Date: 2026-09-16 01:27:46.778858

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cb639f3bea0c'
down_revision = '790cbe896349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'self_registered',
            sa.Boolean(),
            # Alembic renders `db.false()` back out as sa.text('0'), which
            # Postgres refuses on a boolean column. Corrected by hand every
            # time autogenerate adds a boolean.
            server_default=sa.false(),
            nullable=False,
        ))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))

    # Backfill. Everybody who exists before this migration was entered by
    # staff or imported from the church's own records, which is exactly what
    # approval records. Without this line every existing member loses sight of
    # church-wide announcements the moment this deploys.
    op.execute("UPDATE person SET approved_at = created_at WHERE approved_at IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('approved_at')
        batch_op.drop_column('self_registered')

    # ### end Alembic commands ###
