"""Increment 9: groups, meetings, RSVPs, church timezone

Revision ID: ddedc3621d5a
Revises: fbecbb985373
Create Date: 2026-09-02 00:59:51.499384

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ddedc3621d5a'
down_revision = 'fbecbb985373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_pattern', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_group_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group'))
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index('ix_group_church_active', ['church_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_church_id'), ['church_id'], unique=False)

    op.create_table('group_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('meets_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_group_meeting_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_group_meeting_group_id_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_meeting'))
    )
    with op.batch_alter_table('group_meeting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_meeting_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_meeting_group_id'), ['group_id'], unique=False)
        batch_op.create_index('ix_meeting_church_time', ['church_id', 'meets_at'], unique=False)
        batch_op.create_index('ix_meeting_group_time', ['group_id', 'meets_at'], unique=False)

    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('member', 'leader')", name=op.f('ck_group_membership_ck_group_membership_role')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_group_membership_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_group_membership_group_id_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_group_membership_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_membership')),
    sa.UniqueConstraint('group_id', 'person_id', name='uq_group_membership_person_id')
    )
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_membership_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_membership_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_membership_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_membership_church_person', ['church_id', 'person_id'], unique=False)

    op.create_table('meeting_rsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("response IN ('going', 'maybe', 'not_going')", name=op.f('ck_meeting_rsvp_ck_meeting_rsvp_response')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_meeting_rsvp_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['group_meeting.id'], name=op.f('fk_meeting_rsvp_meeting_id_group_meeting'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_meeting_rsvp_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_rsvp')),
    sa.UniqueConstraint('meeting_id', 'person_id', name='uq_meeting_rsvp_person_id')
    )
    with op.batch_alter_table('meeting_rsvp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_rsvp_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_rsvp_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_rsvp_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_rsvp_church_meeting', ['church_id', 'meeting_id', 'response'], unique=False)

    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('meeting_rsvp', schema=None) as batch_op:
        batch_op.drop_index('ix_rsvp_church_meeting')
        batch_op.drop_index(batch_op.f('ix_meeting_rsvp_person_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_rsvp_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_rsvp_church_id'))

    op.drop_table('meeting_rsvp')
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.drop_index('ix_membership_church_person')
        batch_op.drop_index(batch_op.f('ix_group_membership_person_id'))
        batch_op.drop_index(batch_op.f('ix_group_membership_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_membership_church_id'))

    op.drop_table('group_membership')
    with op.batch_alter_table('group_meeting', schema=None) as batch_op:
        batch_op.drop_index('ix_meeting_group_time')
        batch_op.drop_index('ix_meeting_church_time')
        batch_op.drop_index(batch_op.f('ix_group_meeting_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_meeting_church_id'))

    op.drop_table('group_meeting')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_church_id'))
        batch_op.drop_index('ix_group_church_active')

    op.drop_table('group')
    # ### end Alembic commands ###
