"""members can post announcements

Adds church.members_can_announce, on by default. Server default is
sa.true(), hand-fixed: Alembic renders sa.text('1'), which Postgres rejects
for a boolean column.

Revision ID: de2973099ddb
Revises: 763dfd13feab
Create Date: 2026-09-19 10:18:47.436495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2973099ddb'
down_revision = '763dfd13feab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('members_can_announce', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.drop_column('members_can_announce')

    # ### end Alembic commands ###
