"""weekly verse

Revision ID: eaa113743e10
Revises: bb1b1997175b
Create Date: 2026-09-19 14:15:59.453813

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'eaa113743e10'
down_revision = 'bb1b1997175b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('translation', sa.String(length=20), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_weekly_verse_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_weekly_verse_created_by_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_verse')),
    sa.UniqueConstraint('church_id', 'starts_on', name='uq_weekly_verse_week')
    )
    with op.batch_alter_table('weekly_verse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_verse_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_weekly_verse_church_starts', ['church_id', 'starts_on'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_verse', schema=None) as batch_op:
        batch_op.drop_index('ix_weekly_verse_church_starts')
        batch_op.drop_index(batch_op.f('ix_weekly_verse_church_id'))

    op.drop_table('weekly_verse')
    # ### end Alembic commands ###
