"""Increment 4: outbox and notification preferences

Revision ID: f92056a65d90
Revises: 3755f028bed8
Create Date: 2026-08-18 14:39:00.784076

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f92056a65d90'
down_revision = '3755f028bed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('account', 'kids_checkin', 'giving_receipt', 'welcome', 'next_step', 'group', 'announcement', 'digest')", name=op.f('ck_notification_preference_ck_notification_preference_category')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_notification_preference_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_notification_preference_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preference')),
    sa.UniqueConstraint('church_id', 'person_id', 'category', name='uq_notification_preference_person_id')
    )
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preference_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_preference_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_pref_church_person', ['church_id', 'person_id'], unique=False)

    op.create_table('outbox_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('to_name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claim_token', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('account', 'kids_checkin', 'giving_receipt', 'welcome', 'next_step', 'group', 'announcement', 'digest')", name=op.f('ck_outbox_message_ck_outbox_message_category')),
    sa.CheckConstraint("status IN ('queued', 'sent', 'failed', 'suppressed', 'cancelled')", name=op.f('ck_outbox_message_ck_outbox_message_status')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_outbox_message_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name=op.f('fk_outbox_message_created_by_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_outbox_message_person_id_person'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_message')),
    sa.UniqueConstraint('church_id', 'dedupe_key', name='uq_outbox_message_dedupe_key')
    )
    with op.batch_alter_table('outbox_message', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_church_person', ['church_id', 'person_id', 'created_at'], unique=False)
        batch_op.create_index('ix_outbox_church_status', ['church_id', 'status', 'queued_at'], unique=False)
        batch_op.create_index('ix_outbox_claim', ['claim_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_message_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_message_person_id'), ['person_id'], unique=False)
        batch_op.create_index('ix_outbox_status_queued', ['status', 'queued_at'], unique=False)

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_opt_out_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('unsubscribe_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_person_unsubscribe_token'), ['unsubscribe_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_unsubscribe_token'))
        batch_op.drop_column('unsubscribe_token')
        batch_op.drop_column('email_opt_out_at')

    with op.batch_alter_table('outbox_message', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_status_queued')
        batch_op.drop_index(batch_op.f('ix_outbox_message_person_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_message_church_id'))
        batch_op.drop_index('ix_outbox_claim')
        batch_op.drop_index('ix_outbox_church_status')
        batch_op.drop_index('ix_outbox_church_person')

    op.drop_table('outbox_message')
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_index('ix_pref_church_person')
        batch_op.drop_index(batch_op.f('ix_notification_preference_person_id'))
        batch_op.drop_index(batch_op.f('ix_notification_preference_church_id'))

    op.drop_table('notification_preference')
    # ### end Alembic commands ###
