"""Increment 7: giving link-out

Revision ID: fbecbb985373
Revises: 1b05a93c764f
Create Date: 2026-09-02 00:42:20.553000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbecbb985373'
down_revision = '1b05a93c764f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('giving_provider', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('giving_admin_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('giving_form_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.drop_column('giving_form_url')
        batch_op.drop_column('giving_admin_url')
        batch_op.drop_column('giving_provider')

    # ### end Alembic commands ###
