"""Increment 12: conversations, members, messages

Revision ID: fd019c06a90b
Revises: 200c8e06e04d
Create Date: 2026-09-02 12:06:44.837169

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fd019c06a90b'
down_revision = '200c8e06e04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('topic', sa.String(length=240), nullable=True),
    sa.Column('direct_pair', sa.String(length=40), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('announcement', 'room', 'direct')", name=op.f('ck_conversation_ck_conversation_kind')),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_conversation_church_id_church'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation')),
    sa.UniqueConstraint('church_id', 'direct_pair', name='uq_conversation_direct_pair')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_church_id'), ['church_id'], unique=False)
        batch_op.create_index('ix_conversation_church_kind', ['church_id', 'kind', 'is_archived'], unique=False)

    op.create_table('conversation_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_conversation_member_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_conversation_member_conversation_id_conversation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_conversation_member_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_member')),
    sa.UniqueConstraint('conversation_id', 'person_id', name='uq_conversation_member_person_id')
    )
    with op.batch_alter_table('conversation_member', schema=None) as batch_op:
        batch_op.create_index('ix_conv_member_church_person', ['church_id', 'person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_member_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_member_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_member_person_id'), ['person_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('author_person_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_person_id'], ['person.id'], name=op.f('fk_message_author_person_id_person'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], name=op.f('fk_message_church_id_church'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_message_conversation_id_conversation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_author_person_id'), ['author_person_id'], unique=False)
        batch_op.create_index('ix_message_church_conv_time', ['church_id', 'conversation_id', 'sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_message_church_id'))
        batch_op.drop_index('ix_message_church_conv_time')
        batch_op.drop_index(batch_op.f('ix_message_author_person_id'))

    op.drop_table('message')
    with op.batch_alter_table('conversation_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_member_person_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_member_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_member_church_id'))
        batch_op.drop_index('ix_conv_member_church_person')

    op.drop_table('conversation_member')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_church_kind')
        batch_op.drop_index(batch_op.f('ix_conversation_church_id'))

    op.drop_table('conversation')
    # ### end Alembic commands ###
