"""Model package. Import every model here so Alembic autogenerate sees them."""

from app.models.base import (  # noqa: F401
    TenantScoped,
    TimestampMixin,
    UTCDateTime,
    utcnow,
)
from app.models.church import Church  # noqa: F401
from app.models.contact import (  # noqa: F401
    CONTACT_METHODS,
    STATUS_DONE,
    STATUS_DROPPED,
    STATUS_OPEN,
    ContactLog,
    NextStep,
)
from app.models.outbox import (  # noqa: F401
    MAX_ATTEMPTS,
    OUTBOX_STATUSES,
    STATUS_CANCELLED,
    STATUS_FAILED,
    STATUS_QUEUED,
    STATUS_SENT,
    STATUS_SUPPRESSED,
    NotificationPreference,
    OutboxMessage,
)
from app.models.group import (  # noqa: F401
    GROUP_ROLES,
    ROLE_LEADER,
    ROLE_MEMBER,
    RSVP_CHOICES,
    RSVP_GOING,
    RSVP_MAYBE,
    RSVP_NOT_GOING,
    Group,
    GroupMeeting,
    GroupMembership,
    MeetingRSVP,
)
from app.models.password_reset import PasswordResetToken  # noqa: F401
from app.models.person import Household, Person  # noqa: F401
from app.models.service import (  # noqa: F401
    ACCEPTED,
    ASSIGNMENT_STATUSES,
    DECLINED,
    INVITED,
    ITEM_ELEMENT,
    ITEM_KINDS,
    ITEM_SONG,
    Service,
    ServiceAssignment,
    ServiceItem,
    Song,
    Team,
    TeamMembership,
    TeamPosition,
)
from app.models.resource import (  # noqa: F401
    RESOURCE_KINDS,
    RESOURCE_STATUSES,
    STATUS_ARCHIVED,
    STATUS_DRAFT,
    STATUS_PUBLISHED,
    Resource,
    ResourceSession,
    SessionCompletion,
)
from app.models.person_event import (  # noqa: F401
    EVENT_KINDS,
    KIND_CONTACT,
    KIND_CREATED,
    KIND_EMAIL,
    KIND_IMPORTED,
    KIND_NEXT_STEP,
    KIND_NOTE,
    KIND_STAGE_CHANGE,
    PersonEvent,
)
from app.models.user import ROLES, User  # noqa: F401

__all__ = [
    "Church",
    "Household",
    "Person",
    "PersonEvent",
    "ContactLog",
    "NextStep",
    "OutboxMessage",
    "NotificationPreference",
    "PasswordResetToken",
    "Service",
    "ServiceItem",
    "ServiceAssignment",
    "Song",
    "Team",
    "TeamPosition",
    "TeamMembership",
    "INVITED",
    "ACCEPTED",
    "DECLINED",
    "ITEM_SONG",
    "ITEM_ELEMENT",
    "ITEM_KINDS",
    "Group",
    "GroupMembership",
    "GroupMeeting",
    "MeetingRSVP",
    "RSVP_CHOICES",
    "RSVP_GOING",
    "RSVP_MAYBE",
    "RSVP_NOT_GOING",
    "GROUP_ROLES",
    "ROLE_LEADER",
    "ROLE_MEMBER",
    "Resource",
    "ResourceSession",
    "SessionCompletion",
    "RESOURCE_KINDS",
    "STATUS_DRAFT",
    "STATUS_PUBLISHED",
    "STATUS_ARCHIVED",
    "STATUS_QUEUED",
    "STATUS_SENT",
    "STATUS_FAILED",
    "STATUS_SUPPRESSED",
    "STATUS_CANCELLED",
    "MAX_ATTEMPTS",
    "CONTACT_METHODS",
    "STATUS_OPEN",
    "STATUS_DONE",
    "STATUS_DROPPED",
    "EVENT_KINDS",
    "KIND_CREATED",
    "KIND_IMPORTED",
    "KIND_NOTE",
    "KIND_STAGE_CHANGE",
    "KIND_CONTACT",
    "KIND_EMAIL",
    "KIND_NEXT_STEP",
    "User",
    "ROLES",
    "TenantScoped",
    "TimestampMixin",
    "UTCDateTime",
    "utcnow",
]
