"""Model package. Import every model here so Alembic autogenerate sees them."""

from app.models.base import (  # noqa: F401
    TenantScoped,
    TimestampMixin,
    UTCDateTime,
    utcnow,
)
from app.models.church import Church  # noqa: F401
from app.models.contact import (  # noqa: F401
    CONTACT_METHODS,
    STATUS_DONE,
    STATUS_DROPPED,
    STATUS_OPEN,
    ContactLog,
    NextStep,
)
from app.models.outbox import (  # noqa: F401
    MAX_ATTEMPTS,
    OUTBOX_STATUSES,
    STATUS_CANCELLED,
    STATUS_FAILED,
    STATUS_QUEUED,
    STATUS_SENT,
    STATUS_SUPPRESSED,
    NotificationPreference,
    OutboxMessage,
)
from app.models.giving_mirror import (  # noqa: F401
    LAPSE_GRACE_DAYS,
    MATCH_IGNORED,
    MATCH_MATCHED,
    MATCH_STATUSES,
    MATCH_UNMATCHED,
    RECURRING_ACTIVE,
    RECURRING_CANCELLED,
    RECURRING_PAUSED,
    ExternalGift,
    ExternalRecurringGift,
    IntegrationCredential,
)
from app.models.audit import ACTIONS, AuditEvent  # noqa: F401
from app.models.bible import WEB_CODE, WEB_NAME, BibleVerse  # noqa: F401
from app.models.kids import Checkin, CheckinSession  # noqa: F401
from app.models.sequence import (  # noqa: F401
    ENROLLMENT_STATUSES,
    REASON_CONTACT,
    REASON_TARGET_STAGE,
    SequenceEnrollment,
)
from app.models.message import (  # noqa: F401
    CONVERSATION_KINDS,
    KIND_ANNOUNCEMENT,
    KIND_DIRECT,
    KIND_ROOM,
    Conversation,
    ConversationMember,
    Message,
)
from app.models.group import (  # noqa: F401
    GROUP_ROLES,
    ROLE_LEADER,
    ROLE_MEMBER,
    RSVP_CHOICES,
    RSVP_GOING,
    RSVP_MAYBE,
    RSVP_NOT_GOING,
    Group,
    GroupMeeting,
    GroupMembership,
    MeetingRSVP,
)
from app.models.email_verification import EmailVerificationToken  # noqa: F401
from app.models.moderation import (  # noqa: F401
    REPORT_DISMISSED,
    REPORT_OPEN,
    REPORT_REMOVED,
    MessageReport,
    PersonBlock,
)
from app.models.password_reset import PasswordResetToken  # noqa: F401
from app.models.push import PushSubscription  # noqa: F401
from app.models.person import Household, Person  # noqa: F401
from app.models.service import (  # noqa: F401
    ITEM_HEADER,
    ServiceNeed,
    ServiceTemplateItem,
    ServiceType,
    ServiceTypeNeed,
    build_from_type,
    copy_plan,
    ACCEPTED,
    ASSIGNMENT_STATUSES,
    DECLINED,
    INVITED,
    ITEM_ELEMENT,
    ITEM_KINDS,
    ITEM_SONG,
    Service,
    ServiceAssignment,
    ServiceItem,
    Song,
    Team,
    TeamMembership,
    TeamPosition,
)
from app.models.verse import WeeklyVerse, week_of  # noqa: F401
from app.models.resource import (  # noqa: F401
    RESOURCE_KINDS,
    RESOURCE_STATUSES,
    STATUS_ARCHIVED,
    STATUS_DRAFT,
    STATUS_PUBLISHED,
    Resource,
    ResourceSession,
    SessionCompletion,
)
from app.models.person_event import (  # noqa: F401
    EVENT_KINDS,
    KIND_CONTACT,
    KIND_CREATED,
    KIND_EMAIL,
    KIND_IMPORTED,
    KIND_NEXT_STEP,
    KIND_NOTE,
    KIND_STAGE_CHANGE,
    PersonEvent,
)
from app.models.user import ROLES, User  # noqa: F401

__all__ = [
    "WeeklyVerse",
    "week_of",
    "Church",
    "Household",
    "Person",
    "PersonEvent",
    "ContactLog",
    "NextStep",
    "OutboxMessage",
    "NotificationPreference",
    "PasswordResetToken",
    "MessageReport",
    "PersonBlock",
    "EmailVerificationToken",
    "PushSubscription",
    "Service",
    "ServiceItem",
    "ServiceAssignment",
    "Song",
    "Team",
    "TeamPosition",
    "TeamMembership",
    "INVITED",
    "ACCEPTED",
    "DECLINED",
    "ITEM_SONG",
    "ITEM_HEADER",
    "ServiceType",
    "ServiceTemplateItem",
    "ServiceTypeNeed",
    "ServiceNeed",
    "build_from_type",
    "copy_plan",
    "ITEM_ELEMENT",
    "ITEM_KINDS",
    "Conversation",
    "ConversationMember",
    "Message",
    "CONVERSATION_KINDS",
    "KIND_ANNOUNCEMENT",
    "KIND_ROOM",
    "KIND_DIRECT",
    "ExternalGift",
    "ExternalRecurringGift",
    "IntegrationCredential",
    "MATCH_UNMATCHED",
    "MATCH_MATCHED",
    "MATCH_IGNORED",
    "RECURRING_ACTIVE",
    "LAPSE_GRACE_DAYS",
    "SequenceEnrollment",
    "REASON_CONTACT",
    "REASON_TARGET_STAGE",
    "BibleVerse",
    "WEB_CODE",
    "WEB_NAME",
    "AuditEvent",
    "ACTIONS",
    "Checkin",
    "CheckinSession",
    "Group",
    "GroupMembership",
    "GroupMeeting",
    "MeetingRSVP",
    "RSVP_CHOICES",
    "RSVP_GOING",
    "RSVP_MAYBE",
    "RSVP_NOT_GOING",
    "GROUP_ROLES",
    "ROLE_LEADER",
    "ROLE_MEMBER",
    "Resource",
    "ResourceSession",
    "SessionCompletion",
    "RESOURCE_KINDS",
    "STATUS_DRAFT",
    "STATUS_PUBLISHED",
    "STATUS_ARCHIVED",
    "STATUS_QUEUED",
    "STATUS_SENT",
    "STATUS_FAILED",
    "STATUS_SUPPRESSED",
    "STATUS_CANCELLED",
    "MAX_ATTEMPTS",
    "CONTACT_METHODS",
    "STATUS_OPEN",
    "STATUS_DONE",
    "STATUS_DROPPED",
    "EVENT_KINDS",
    "KIND_CREATED",
    "KIND_IMPORTED",
    "KIND_NOTE",
    "KIND_STAGE_CHANGE",
    "KIND_CONTACT",
    "KIND_EMAIL",
    "KIND_NEXT_STEP",
    "User",
    "ROLES",
    "TenantScoped",
    "TimestampMixin",
    "UTCDateTime",
    "utcnow",
]
